export const t = {
  notFound: 'This page could not be found',
  notFoundDescription: 'The link may have changed. Return to your notification overview.',
  returnOverview: 'Return to overview',
  name: 'NotifyHub',
  tagline: 'One gateway. Every notification.',
  overview: 'Overview',
  workspace: 'Workspace',
  selfHosted: 'Your infrastructure. Your control.',
  theme: 'Switch color theme',
  title: 'Your notification control room',
  description: 'Route messages from your applications to the places that matter.',
  phase: 'Getting started',
  status: 'Your gateway is waiting for setup. Account and delivery services will be available once configuration is complete.',
  health: 'API connection',
  checking: 'Checking connection…',
  connected: 'API is reachable',
  unavailable: 'API is unavailable. Start the API and try again.',
  retry: 'Retry connection',
  channels: 'Delivery channels',
  channelsDescription: 'A single integration for your notification destinations.',
  channelNames: ['Email', 'Telegram', 'Discord', 'Webhook', 'Web Push'],
  activity: 'Message activity',
  noMessages: 'No notifications yet',
  noMessagesDescription: 'Once your workspace is ready, connect an application and create your first routing rule.',
  skip: 'Skip to main content',
};

