export const t = {
  signIn: 'Sign in',
  signOut: 'Sign out',
  signedIn: 'Signed in',
  email: 'Email address',
  password: 'Password',
  secureAccess: 'Secure workspace access',
  signInDescription: 'Welcome back. Sign in to your NotifyHub account.',
  authStoryTitle: 'Your notifications, together.',
  authStoryDescription: 'A quiet, focused space to connect applications and stay in control of every delivery.',
  setupMfa: 'Protect your account',
  setupMfaDescription: 'Add NotifyHub to your authenticator app, then enter the six-digit code to finish setup.',
  verifyMfa: 'Verify your identity',
  verifyMfaDescription: 'Enter a code from your authenticator app to continue securely.',
  authenticatorKey: 'Manual setup key',
  authenticatorInstructions: 'Choose a time-based account in your authenticator app. Use NotifyHub as the issuer and your email as the account name.',
  verificationCode: 'Six-digit code',
  recoveryCode: 'Recovery code',
  useRecovery: 'Use a recovery code instead',
  useAuthenticator: 'Use my authenticator instead',
  signingIn: 'Please wait…',
  verifyContinue: 'Verify and continue',
  startAgain: 'Start again',
  saveRecovery: 'Save your recovery codes',
  recoveryDescription: 'Keep these codes in a secure place. Each one can be used once if you lose access to your authenticator.',
  recoveryCodes: 'One-time recovery codes',
  recoveryOnce: 'These codes are shown once and are not saved by the browser.',
  savedContinue: 'I have saved my codes',
  inviteOnly: 'Accounts are managed by your instance administrator. Contact them if you need access.',
  authErrors: {
    NETWORK: 'We could not connect. Check your connection and try again.',
    LOGIN_FAILED: 'Sign-in could not be completed. Check your details or start again.',
    NOT_CONFIGURED: 'Account access is not configured yet. Contact your administrator.',
    ORIGIN_DENIED: 'Secure account access requires HTTPS and an approved site address.',
    RATE_LIMITED: 'Too many attempts. Wait a moment before trying again.',
    INVALID_RESPONSE: 'The server returned an unexpected response. Try again.',
    BROWSER_UNSUPPORTED: 'This browser cannot coordinate secure sessions. Use a current supported browser.',
  } as Record<string, string>,
  notFound: 'This page could not be found',
  notFoundDescription: 'The link may have changed. Return to your notification overview.',
  returnOverview: 'Return to overview',
  name: 'NotifyHub',
  tagline: 'One gateway. Every notification.',
  overview: 'Overview',
  workspace: 'Workspace',
  selfHosted: 'Your infrastructure. Your control.',
  theme: 'Switch color theme',
  title: 'Your notification control room',
  description: 'Route messages from your applications to the places that matter.',
  phase: 'Getting started',
  status: 'Your gateway is waiting for setup. Account and delivery services will be available once configuration is complete.',
  health: 'API connection',
  checking: 'Checking connection…',
  connected: 'API is reachable',
  unavailable: 'API is unavailable. Start the API and try again.',
  retry: 'Retry connection',
  channels: 'Delivery channels',
  channelsDescription: 'A single integration for your notification destinations.',
  channelNames: ['Email', 'Telegram', 'Discord', 'Webhook', 'Web Push'],
  activity: 'Message activity',
  noMessages: 'No notifications yet',
  noMessagesDescription: 'Once your workspace is ready, connect an application and create your first routing rule.',
  skip: 'Skip to main content',
};

